$(document).ready(function(){
	$('#evHDp').click(function(){
		$('#evCl').fadeIn(500);
	})
	$('#evClo').click(function(){
		$('#evCl').fadeOut(500);
	})
	$('#taHDp').click(function(){
		$('#taCl').fadeIn(500);
	})
	$('#taClo').click(function(){
		$('#taCl').fadeOut(500);
	})
	$('#pdHDp').click(function(){
		$('#pdCl').fadeIn(500);
	})
	$('#pdClo').click(function(){
		$('#pdCl').fadeOut(500);
	})
	$('#woHDp').click(function(){
		$('#woCl').fadeIn(500);
	})
	$('#woClo').click(function(){
		$('#woCl').fadeOut(500);
	})
	$('#msHDp').click(function(){
		$('#msCl').fadeIn(500);
	})
	$('#msClo').click(function(){
		$('#msCl').fadeOut(500);
	})
	$('#impr').click(function(){
		$('#impr').css('color','#FF7D42');
		$('#ev_x').css('color','black');
		$('#verse').css('color','black');
		$('#dubwa').css('color','black');
		$('#madad').css('color','black');
		$('#coff').css('color','black');
		$('#scifi').css('color','black');
		$('#scifiDetails').fadeOut(250);
		$('#ev_xDetails').fadeOut(250);
		$('#verseDetails').fadeOut(250);
		$('#coffDetails').fadeOut(250);
		$('#dubwaDetails').fadeOut(250);
		$('#madadDetails').fadeOut(250);
		$('#imprDetails').fadeIn(250);
	})
	$('#ev_x').click(function(){
		$('#ev_x').css('color','#FF7D42');
		$('#impr').css('color','black');
		$('#verse').css('color','black');
		$('#dubwa').css('color','black');
		$('#madad').css('color','black');
		$('#coff').css('color','black');
		$('#scifi').css('color','black');
		$('#scifiDetails').fadeOut(250);
		$('#verseDetails').fadeOut(250);
		$('#coffDetails').fadeOut(250);
		$('#dubwaDetails').fadeOut(250);
		$('#madadDetails').fadeOut(250);
		$('#imprDetails').fadeOut(250);
		$('#ev_xDetails').fadeIn(250);
	})
	$('#verse').click(function(){
		$('#verse').css('color','#FF7D42');
		$('#ev_x').css('color','black');
		$('#impr').css('color','black');
		$('#dubwa').css('color','black');
		$('#madad').css('color','black');
		$('#coff').css('color','black');
		$('#scifi').css('color','black');
		$('#scifiDetails').fadeOut(250);
		$('#ev_xDetails').fadeOut(250);
		$('#imprDetails').fadeOut(250);
		$('#coffDetails').fadeOut(250);
		$('#dubwaDetails').fadeOut(250);
		$('#madadDetails').fadeOut(250);
		$('#verseDetails').fadeIn(250);
	})
	$('#madad').click(function(){
		$('#madad').css('color','#FF7D42');
		$('#ev_x').css('color','black');
		$('#verse').css('color','black');
		$('#dubwa').css('color','black');
		$('#impr').css('color','black');
		$('#coff').css('color','black');
		$('#scifi').css('color','black');
		$('#scifiDetails').fadeOut(250);
		$('#ev_xDetails').fadeOut(250);
		$('#verseDetails').fadeOut(250);
		$('#coffDetails').fadeOut(250);
		$('#dubwaDetails').fadeOut(250);
		$('#imprDetails').fadeOut(250);
		$('#madadDetails').fadeIn(250)
	})
	$('#dubwa').click(function(){
		$('#dubwa').css('color','#FF7D42');
		$('#ev_x').css('color','black');
		$('#verse').css('color','black');
		$('#impr').css('color','black');
		$('#madad').css('color','black');
		$('#coff').css('color','black');
		$('#scifi').css('color','black');
		$('#scifiDetails').fadeOut(250);
		$('#ev_xDetails').fadeOut(250);
		$('#verseDetails').fadeOut(250);
		$('#coffDetails').fadeOut(250);
		$('#madadDetails').fadeOut(250);
		$('#imprDetails').fadeOut(250);
		$('#dubwaDetails').fadeIn(250);
	})
	$('#coff').click(function(){
		$('#coff').css('color','#FF7D42');
		$('#ev_x').css('color','black');
		$('#verse').css('color','black');
		$('#dubwa').css('color','black');
		$('#madad').css('color','black');
		$('#impr').css('color','black');
		$('#scifi').css('color','black');
		$('#scifiDetails').fadeOut(250);
		$('#ev_xDetails').fadeOut(250);
		$('#verseDetails').fadeOut(250);
		$('#dubwaDetails').fadeOut(250);
		$('#madadDetails').fadeOut(250);
		$('#imprDetails').fadeOut(250);
		$('#coffDetails').fadeIn(250);
	})
	$('#scifi').click(function(){
		$('#scifi').css('color','#FF7D42');
		$('#ev_x').css('color','black');
		$('#verse').css('color','black');
		$('#dubwa').css('color','black');
		$('#madad').css('color','black');
		$('#coff').css('color','black');
		$('#impr').css('color','black');
		$('#ev_xDetails').fadeOut(250);
		$('#verseDetails').fadeOut(250);
		$('#dubwaDetails').fadeOut(250);
		$('#madadDetails').fadeOut(250);
		$('#imprDetails').fadeOut(250);
		$('#coffDetails').fadeOut(250);
		$('#scifiDetails').fadeIn(250);
	})

	$('#driz').click(function(){
		$('#driz').css('color','#FF7D42');
		$('#reaz').css('color','black');
		$('#book').css('color','black');
		$('#board').css('color','black');
		$('#movie').css('color','black');
		$('#star').css('color','black');
		$('#teen').css('color','black');
		$('#teenDetails').fadeOut(250);
		$('#reazDetails').fadeOut(250);
		$('#bookDetails').fadeOut(250);
		$('#starDetails').fadeOut(250);
		$('#boardDetails').fadeOut(250);
		$('#movieDetails').fadeOut(250);
		$('#drizDetails').fadeIn(250);
	})
	$('#reaz').click(function(){
		$('#reaz').css('color','#FF7D42');
		$('#driz').css('color','black');
		$('#book').css('color','black');
		$('#board').css('color','black');
		$('#movie').css('color','black');
		$('#star').css('color','black');
		$('#teen').css('color','black');
		$('#teenDetails').fadeOut(250);
		$('#bookDetails').fadeOut(250);
		$('#starDetails').fadeOut(250);
		$('#boardDetails').fadeOut(250);
		$('#movieDetails').fadeOut(250);
		$('#drizDetails').fadeOut(250);
		$('#reazDetails').fadeIn(250);
	})
	$('#book').click(function(){
		$('#book').css('color','#FF7D42');
		$('#reaz').css('color','black');
		$('#driz').css('color','black');
		$('#board').css('color','black');
		$('#movie').css('color','black');
		$('#star').css('color','black');
		$('#teen').css('color','black');
		$('#teenDetails').fadeOut(250);
		$('#reazDetails').fadeOut(250);
		$('#drizDetails').fadeOut(250);
		$('#starDetails').fadeOut(250);
		$('#boardDetails').fadeOut(250);
		$('#movieDetails').fadeOut(250);
		$('#bookDetails').fadeIn(250);
	})
	$('#movie').click(function(){
		$('#movie').css('color','#FF7D42');
		$('#reaz').css('color','black');
		$('#book').css('color','black');
		$('#board').css('color','black');
		$('#driz').css('color','black');
		$('#star').css('color','black');
		$('#teen').css('color','black');
		$('#teenDetails').fadeOut(250);
		$('#reazDetails').fadeOut(250);
		$('#bookDetails').fadeOut(250);
		$('#starDetails').fadeOut(250);
		$('#boardDetails').fadeOut(250);
		$('#drizDetails').fadeOut(250);
		$('#movieDetails').fadeIn(250);
	})
	$('#board').click(function(){
		$('#board').css('color','#FF7D42');
		$('#reaz').css('color','black');
		$('#book').css('color','black');
		$('#driz').css('color','black');
		$('#movie').css('color','black');
		$('#star').css('color','black');
		$('#teen').css('color','black');
		$('#teenDetails').fadeOut(250);
		$('#reazDetails').fadeOut(250);
		$('#bookDetails').fadeOut(250);
		$('#starDetails').fadeOut(250);
		$('#movieDetails').fadeOut(250);
		$('#drizDetails').fadeOut(250);
		$('#boardDetails').fadeIn(250);
	})
	$('#star').click(function(){
		$('#star').css('color','#FF7D42');
		$('#reaz').css('color','black');
		$('#book').css('color','black');
		$('#board').css('color','black');
		$('#movie').css('color','black');
		$('#driz').css('color','black');
		$('#teen').css('color','black');
		$('#teenDetails').fadeOut(250);
		$('#reazDetails').fadeOut(250);
		$('#bookDetails').fadeOut(250);
		$('#boardDetails').fadeOut(250);
		$('#movieDetails').fadeOut(250);
		$('#drizDetails').fadeOut(250);
		$('#starDetails').fadeIn(250);
	})
	$('#teen').click(function(){
		$('#teen').css('color','#FF7D42');
		$('#reaz').css('color','black');
		$('#book').css('color','black');
		$('#board').css('color','black');
		$('#movie').css('color','black');
		$('#driz').css('color','black');
		$('#star').css('color','black');
		$('#reazDetails').fadeOut(250);
		$('#bookDetails').fadeOut(250);
		$('#boardDetails').fadeOut(250);
		$('#movieDetails').fadeOut(250);
		$('#drizDetails').fadeOut(250);
		$('#starDetails').fadeOut(250);
		$('#teenDetails').fadeIn(250);
	})
})